---
- name: Install Jenkins on Ubuntu
  hosts: all
  become: true
  tasks:
    - name: Update apt package cache and install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - openjdk-11-jdk
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release

    - name: Add Jenkins repository key
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present

    - name: Add Jenkins repository
      apt_repository:
        repo: "deb https://pkg.jenkins.io/debian binary/"
        state: present
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes
