version: '3'

services:
  api:
    image: vikaschenny/demo-api:v1.0
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB=demo
      - DBUSER=root
      - DBPASS=password
      - DBHOST=DB_HOST
      - DBPORT=3306

  web:
    image: vikaschenny/demo-web:v1.0
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - API_HOST=http://api:3000  # Assuming 'api' is the service name
    depends_on:
      - api
